### ISSUE TITLE
[FEATURE REQUEST] Add greeting action

### ISSUE THREAD

**Issue by KendallDoesCoding** [Adarsh-jaiss/journey-book#18]
**Is your feature request related to a problem? Please describe.**
Add a greeting github action to the repo to display a greeting message, when user makes their first issue or PR in this repo.

**Describe the solution you'd like**
Welcome contributors to this project!

**Additional context**
I can work on this, but please provide me with the greeting message you want displayed when the user creates their first issue and PR @Adarsh-jaiss

**Comment by Adarsh-jaiss** [comment]
-- Thank you for contributing to journey book
-- we love you and your pr (heart emoji)
-- Waiting for you another pr

**Comment by Adarsh-jaiss** [comment]
-- you can also add something from your side :)

**Comment by KendallDoesCoding** [comment]
LGTM, i don't think you can add 3 seprate lines though so here's what I'll add:

**PR GREETING (FIRST PR BY CONTRIBUTOR)**
Thank you for contributing to Journey Book. We love you and your PR ❤️ . Waiting for you to contribute again to Journey Book

**ISSUE GREETING (FIRST ISSUE BY CONTRIBUTOR)**
Thank you for contributing to Journey Book. We love you and your Issue ❤️ . Your issues, really help us with our project... Waiting for you to contribute again to Journey Book.

Idk if the heart emoji will work, but I will try!

@Adarsh-jaiss Please let me know if you want a message to display everytime or only the first time, EddieHubCommunity has a message display always when users make PR's but it's annoying for email notifcs in my email, so I think the first issue/pr greeting is good enough.

**Comment by Adarsh-jaiss** [comment]
> > -- i want it for everytime
> 
> Idk how to do that, will refer to Linkfree and see how they do it.

let it be ,do it for one time

**Comment by KendallDoesCoding** [comment]
> Thank you for contributing to Journey Book. We love you and your Issue ❤️ . Your issues, really help us with our project... Waiting for you to contribute again to Journey Book.

almost missed this xD

**Comment by KendallDoesCoding** [comment]
@Adarsh-jaiss There's no :congrats: emoji there's only ㊗️

**Comment by Adarsh-jaiss** [comment]
no that's not 
let me show you

**Comment by KendallDoesCoding** [comment]
> no that's not let me show you

Yeah ik, it comes under :/congratulations: tho

**Comment by Adarsh-jaiss** [comment]
🎉

**Comment by KendallDoesCoding** [comment]
Thx

**Comment by Adarsh-jaiss** [comment]
👍
