### ISSUE TITLE
[DOCS] Add contributing guidelines

### ISSUE THREAD

**Issue by KendallDoesCoding** [Adarsh-jaiss/journey-book#20]

**Comment by Adarsh-jaiss** [comment]
so, you mean i have to add the git commands for contributing and explain the whole process

**Comment by KendallDoesCoding** [comment]
> so, you mean i have to add the git commands for contributing and explain the whole process ?

No, add contributing guidelines that for ex, what kinda PR's will be accepted in this repo, but it's not really needed coz this repo is to share your journey, so you can close this issue :)

**Comment by Adarsh-jaiss** [comment]
Okay, just leave it :)
