### ISSUE TITLE
Add hashtags to repo.

### ISSUE THREAD

**Issue by KendallDoesCoding** [Adarsh-jaiss/journey-book#3]
Add custom hashtags to the repo... This drags attention to the repo, which as you told me, you want people to share their journey, so it may drag people interested in the project?

![image](https://user-images.githubusercontent.com/84712013/157237532-57c8d3f1-19d2-47ff-a5df-9aac068dbea2.png)

**Comment by Adarsh-jaiss** [comment]
Okay I am gonna add this😃

**Comment by Adarsh-jaiss** [comment]
done :)

**Comment by KendallDoesCoding** [comment]
> Okay I am gonna add this😃

@Adarsh-jaiss You got me wrong, I didn't say add exactly those hashtags, those were for my repo, for this repo you should add stuff like journey, experiences, open-source, coding-life, coding, etc

**Comment by KendallDoesCoding** [comment]
I would make the edits if I could, but only the owner can :)

**Comment by Adarsh-jaiss** [comment]
-- okay I gave understood and make those changes

**Comment by KendallDoesCoding** [comment]
@Adarsh-jaiss Thanks. content-creators can be removed in my opinion though.
