### ISSUE TITLE
[DOCS] Add header image to `README.md`

### ISSUE THREAD

**Issue by vikasganiga05** [Adarsh-jaiss/journey-book#30]
**Is your feature request related to a problem? Please describe.**
No, it's just an improvement to `README.md`. Add header image to the top of the readme file. Which makes the `README.md` file look attractive.

**Describe the solution you'd like**
I used a tool called [GitHub Socialify](https://socialify.git.ci/) to generate the following header images :point_down:.

> ![journey-book](https://socialify.git.ci/Adarsh-jaiss/journey-book/image?description=1&font=Inter&forks=1&issues=1&logo=https%3A%2F%2Fcdn2.iconfinder.com%2Fdata%2Ficons%2Fgeest-travel-kit%2F128%2Ftravel_journey-13-512.png&name=1&pattern=Solid&pulls=1&stargazers=1&theme=Dark)
> [Customize This :point_up:](https://socialify.git.ci/Adarsh-jaiss/journey-book?description=1&font=Inter&forks=1&issues=1&logo=https%3A%2F%2Fcdn2.iconfinder.com%2Fdata%2Ficons%2Fgeest-travel-kit%2F128%2Ftravel_journey-13-512.png&name=1&pattern=Solid&pulls=1&stargazers=1&theme=Dark)

> ![journey-book](https://socialify.git.ci/Adarsh-jaiss/journey-book/image?description=1&font=Inter&forks=1&issues=1&logo=https%3A%2F%2Fcdn2.iconfinder.com%2Fdata%2Ficons%2Fgeest-travel-kit%2F128%2Ftravel_journey-13-512.png&name=1&pattern=Solid&pulls=1&stargazers=1&theme=Light)
> [Customize This :point_up: ](https://socialify.git.ci/Adarsh-jaiss/journey-book?description=1&font=Inter&forks=1&issues=1&logo=https%3A%2F%2Fcdn2.iconfinder.com%2Fdata%2Ficons%2Fgeest-travel-kit%2F128%2Ftravel_journey-13-512.png&name=1&pattern=Solid&pulls=1&stargazers=1&theme=Light)

**Describe alternatives you've considered**
if you don't want to use tool generated image. You can create it from scratch :slightly_smiling_face:.

**Additional context**
No additional context.

**Comment by Adarsh-jaiss** [comment]
The first one with dark theme looks great 👍

**Comment by vikasganiga05** [comment]
Done :+1:
