### ISSUE TITLE
[FEATURE REQUEST] Create directory in repo called "journeys" where people can add their journey

### ISSUE THREAD

**Issue by KendallDoesCoding** [Adarsh-jaiss/journey-book#33]
Write now, users have to share their journey's in the main directory, I think it will be better if they share it in a .md file within a directory called, "journeys"

I think, doing this may also help with #1 , but I aren't sure, @vikasganiga05 please confirm

**Comment by Adarsh-jaiss** [comment]
Yeah you are right kendall 
Hey @vikasganiga05  please confirm it

**Comment by Adarsh-jaiss** [comment]
-- okay let me see, how can I do that. Because genuinely I have no ideas about that :)

**Comment by KendallDoesCoding** [comment]
Will get to work on this now.
