### ISSUE TITLE
[TYPO] 'webiste' instead of 'website'

### ISSUE THREAD

**Issue by KendallDoesCoding** [Adarsh-jaiss/journey-book#35]
**Describe the bug**
The repo description reads as 'webiste' instead of 'website'. Hence, the banner as well is messed up

**Additional context**
@Adarsh-jaiss - Only you can fix this as no one but the repo owner can edit the description of the repo

Thanks @virejdasani for bringing this up to me.

**Comment by Adarsh-jaiss** [comment]
👍👍

**Comment by Adarsh-jaiss** [comment]
It's done 👍 kindly check that out

**Comment by KendallDoesCoding** [comment]
@Adarsh-jaiss now the b is missing, it's currenctly 'wesite' not 'website'

**Comment by Adarsh-jaiss** [comment]
Hahaha 😄😄let me check

**Comment by KendallDoesCoding** [comment]
Perfect, I'll fix the banner.

**Comment by KendallDoesCoding** [comment]
> Perfect, I'll fix the banner.

The banner should be fixed within a hour. I don't have to do anything. Thanks
