### ISSUE TITLE
Issue with README.md on Website

### ISSUE THREAD

**Issue by KendallDoesCoding** [Adarsh-jaiss/journey-book#37]
The README.md is messed up on the website for some reason.

Preview: https://adarsh-jaiss.github.io/journey-book/

@vikasganiga05 @Adarsh-jaiss @TechStudent11 - do yall know what the cause of this is?

**Comment by Adarsh-jaiss** [comment]
Actually I don't, vikas do you have any idea?

**Comment by vikasganiga05** [comment]
> Actually I don't, vikas do you have any idea?

Yes, This is because there is an unclosed `<a>` tag on line 8 in the `README.md` file.

https://github.com/Adarsh-jaiss/journey-book/blob/76edbbafd856b2d79d85b2399a537a7f8f3d3649/README.md?plain=1#L8

**Comment by KendallDoesCoding** [comment]
> > Actually I don't, vikas do you have any idea?
> 
> Yes, This is because there is an unclosed `<a>` tag on line 8 in the `README.md` file.
> 
> https://github.com/Adarsh-jaiss/journey-book/blob/76edbbafd856b2d79d85b2399a537a7f8f3d3649/README.md?plain=1#L8

Oh, will fix this. Thanks for debugging it @vikasganiga05

**Comment by vikasganiga05** [comment]
> > > Actually I don't, vikas do you have any idea?
> > 
> > 
> > Yes, This is because there is an unclosed `<a>` tag on line 8 in the `README.md` file.
> > https://github.com/Adarsh-jaiss/journey-book/blob/76edbbafd856b2d79d85b2399a537a7f8f3d3649/README.md?plain=1#L8
> 
> Oh, will fix this. Thanks for debugging it @vikasganiga05

Most welcome :slightly_smiling_face:
