### ISSUE TITLE
[DOCS] Add issue templates

### ISSUE THREAD

**Issue by KendallDoesCoding** [Adarsh-jaiss/journey-book#6]

**Comment by Adarsh-jaiss** [comment]
i'm gonna add it

**Comment by Adarsh-jaiss** [comment]
-- it is done 👍 
-- reopen this issue if you wanna make changes or wanna add more issue templates :)

**Comment by Adarsh-jaiss** [comment]
kindly check out discussions tab of this repository :)

**Comment by KendallDoesCoding** [comment]
@Adarsh-jaiss Thanks, please review https://github.com/Adarsh-jaiss/journey-book/discussions/13 on the issue templates.
